---
title: Taller de Análisis Económico de intervenciones en salud para la toma de decisiones
subtitle: Bogotá, Colombia, junio de 2024
editor: visual
format: 
  html:
    link-external-newwindow: true
css: styles.css
editor_options: 
  chunk_output_type: console
bibliography: references.bib
---

# Calendario de talleres

+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Fecha     | Hora programada | Tema                                                                                                    | Versión inglesa                                                                                                                |
+===========+=================+=========================================================================================================+================================================================================================================================+
| Martes    | 9:00 - 9:30 am  | Bienvenida y presentaciones                                                                             | Welcome                                                                                                                        |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 9:30 - 10:00    | [Introducción al análisis de decisiones](lectures/ESP_lec_1a.introduction-to-decision-analysis.qmd)     | [Introduction to Decision Analysis](lectures/lec_1a.introduction-to-decision-analysis.qmd "Introduction to Decision Analysis") |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 10:00-11:00     | [Árboles de decisión y probabilidades](lectures/ESP_lec_2.decision-trees-and-probabilities.qmd)         | [Decision Trees](lectures/lec_2.decision-trees-and-probabilities.qmd "Decision Trees and Probabilities")                       |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 11:00-11:15     | Café                                                                                                    | Break                                                                                                                          |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 11:15 - 12:00   | [Caso de estudio: Probabilidades y árboles de decisión](case-studies/ESP_cs_prob-decision.html)         | [Case Study: Decision Trees](case-studies/cs_prob-decision.html)                                                               |
|           |                 |                                                                                                         |                                                                                                                                |
|           |                 | [Respuestas](case-studies/answer-keys/ESP_cs_decision-tree.pdf)                                         |                                                                                                                                |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 12:00 - 1:15 pm | Café                                                                                                    | Break                                                                                                                          |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 1:45 - 2:45 pm  | [Caso de estudio: Construir un árbol de decisión en Excel](case-studies/answer-keys/cs1_PE_v1_ANS.xlsx) | [Case Study: Excel](case-studies/cs_decision-tree-excel.qmd)                                                                   |
|           |                 |                                                                                                         |                                                                                                                                |
|           |                 | [Respuestas](case-studies/answer-keys/cs1_PE_v1_ANS.xlsx)                                               |                                                                                                                                |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 2:45 - 4:00 pm  |                                                                                                         |                                                                                                                                |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Miércoles | 9:00-9:15       | [Recapitulación y demostración del análisis de umbrales en Amua](lectures/ESP_lec_day1-review.qmd)      | [Recap and Demonstration of Threshold Analysis in Amua](lectures/lec_day1-review.qmd)                                          |
|           |                 |                                                                                                         |                                                                                                                                |
|           |                 | [Umbrales de tratamiento y valor de la información](lectures/ESP_lec_4a.trt-thresholds-voi)             | [Treatment Thresholds and Value of Information](lectures/lec_4a.trt-thresholds-voi)                                            |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 9:15 - 10:15    | [Caso de estudio: Construir un árbol de decisión en Amua](case-studies/ESP_cs_decision-tree-amua.qmd)   | [Case Study: Amua](case-studies/cs_decision-tree-amua.qmd)                                                                     |
|           |                 |                                                                                                         |                                                                                                                                |
|           |                 | [Amua model](case-studies/cs_amua-decision-tree.amua)                                                   |                                                                                                                                |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 10:15 - 11:00   | [Fundamentos CEA 1: Costos](lectures/ESP_lec_5a.cea-fundamentals1.qmd)                                  | [Valuing Costs](lectures/lec_5a.cea-fundamentals1.qmd "Costs")                                                                 |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 11:00 - 11:05   | Café                                                                                                    | Break                                                                                                                          |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 11:05 - 12:00   | [Fundamentos CEA 2: Resultados sanitarios](lectures/ESP_lec_5b.cea-fundamentals2.qmd)                   | [Health Outcomes](lectures/lec_5b.cea-fundamentals2.qmd "Health outcomes")                                                     |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 12:00 - 1:40    | Almuerzo                                                                                                | Lunch                                                                                                                          |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 1:40 - 2:45     |                                                                                                         | Group Discussion of Firework Injury Policy Brief                                                                               |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 2:45 - 4:00     | [Caso de estudio: Lesiones por pólvora pirotécnica](case-studies/ESP_cs_injury-decision-tree.qmd)       | [Case Study: Firework Injuries in Colombia](case-studies/cs_injury-decision-tree.qmd)                                          |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 4:00 - 4:45     | [Fundamentos del ACE 3: Análisis coste-eficacia incremental](lectures/ESP_lec_6.ICERs.qmd)              | [ICERs](lectures/lec_6.ICERs.qmd "Incremental CEA")                                                                            |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Jueves    | 9:00-9:15       | Resumen diario                                                                                          |                                                                                                                                |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 9:15 - 10:30    | [Fundamentos del ACE 3: Análisis coste-eficacia incremental](lectures/ESP_lec_6.ICERs.qmd)              | [ICERs](lectures/lec_6.ICERs.qmd "Incremental CEA")                                                                            |
|           |                 |                                                                                                         |                                                                                                                                |
|           |                 | [Caso de estudio: Análisis coste-eficacia incremental](case-studies/ESP_cs_icer.html)                   | [Case Study: ICERs](case-studies/cs_icer.qmd)                                                                                  |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 10:45 - 12:00   | [Modelos de Markov](lectures/ESP_lec_7.MarkovModels1.qmd)                                               | [Markov Models](lectures/lec_7.MarkovModels1.qmd)                                                                              |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 12:00 - 1:15    | Almuerzo                                                                                                | Lunch                                                                                                                          |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 1:15 - 4:00     | [Caso de estudio: Modelos de Markov](case-studies/ESP_cs_injury-markov.qmd)                             | [Case Study: Firework Injury Model (Markov)](case-studies/cs_injury-markov.qmd)                                                |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Viernes   | 9:00-9:15       | Resumen diario                                                                                          | Recap                                                                                                                          |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 9:15 - 10:00    | [Análisis determinista y de escenarios](lectures/ESP_lec_sensitivity.qmd)                               | [Deterministic and Sensitivity Analysis](lectures/lec_sensitivity.qmd)                                                         |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 10:00 - 10:15   | Café                                                                                                    | Break                                                                                                                          |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 10:15 - 11:15   | [Técnicas avanzadas de modelización](lectures/ESP_lec_advanced-modeling-techniques.qmd)                 | [Advanced modeling techniques](lectures/lec_advanced-modeling-techniques.qmd)                                                  |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|           | 11:15 - 11:45   | Ceremonia de entrega de certificados                                                                    | Closing Ceremony                                                                                                               |
+-----------+-----------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[10,20,30,30\]"}
